### ISSUE TITLE
Simplify the CSS code for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [clhallstar/prj-rev-bwfs-dasmoto#5]
It is a good idea to try and simplify the CSS code as much as possible to make the code cleaner and to remove repetitive code. For instance, there are several elements with the same font-family and font-weight property values. You can simplify by applying it at once like

```css
h1, h2, span {
  font-family: Helvetica;
  font-weight: bold;
}
```
